fodScanRepository implementation
hmcts/ccd-user-profile-api pull request #409
Opened 2021-06-24 09:49 UTC by kaanaktas

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CCD-1257

### Change description ###

Implementation of fodScanRepository

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-07-01 14:07 UTC, MSancaktutar commented on config/fortify-client.properties
> +fortify.client.unacceptableSeverity=HIGH
default should be Low, we shouldn't need to set it here.

2021-07-01 14:08 UTC, MSancaktutar commented on config/fortify-client.properties
> +fortify.client.releaseId=65430
only this line should stay.

2021-07-01 14:09 UTC, MSancaktutar commented on build.gradle
> +    testCompile "com.github.hmcts:fortify-client:0.0.3.ccd-1253.1:all"
will need to be replaced with stable release 1.0.0, when ready.

2021-07-01 14:09 UTC, MSancaktutar requested changes
Only minor comments to be actioned please, otherwise all good.

2021-07-01 14:10 UTC, MSancaktutar commented on Jenkinsfile_nightly
> +    enableDbMigration('ccd')
let's raise a separate PR for this line and merge it, so that this PR contains only its own changes.

2021-07-05 09:14 UTC, MSancaktutar requested changes
Please also fit in the after() clause for Fortify Scan stage to publish the scan report on the build.

2021-07-05 10:10 UTC, MSancaktutar approved these changes
LGTM.
Library branch selection will obviously be removed before merging this. Many thanks.

2021-07-07 17:06 UTC, MSancaktutar approved these changes
LGTM - just please remove the branch tag from pipeline library.

2021-07-08 11:32 UTC, kaanaktas commented
> LGTM.
> Library branch selection will obviously be removed before merging this. Many thanks.

jenkins library has been merged and the library branch tag has been removed.

2021-07-15 13:16 UTC, merged